apiVersion: apps/v1
kind: Deployment
metadata:
  name: Minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: api
        image: okteto/hello-world:java-gradle
        imagePullPolicy: Always
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: Minecraft
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: hello-world
spec:
  type: ClusterIP
  ports:
    - name: Minecraft
      port: 8888
  selector:
    app: hello-world
